# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://docs.astronomer.io/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues


# this connection connects to the postgres database hosting Airflow's metastore for a small example
# please note that you should not use this database to store any data in a production context!!

airflow:
  connections:
    - conn_id: postgres_conn
      conn_type: postgres
      conn_host: host.docker.internal
      conn_login: postgres
      conn_password: postgres
      conn_port: 5432

